services:
  frontend:
    image: TU_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tienda-tech-frontend:latest
    container_name: tienda-tech-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: TU_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/tienda-tech-backend:latest
    container_name: tienda-tech-backend
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_PORT: "3306"
    ports:
      - "3001:3001"
